workflows:
  heic-converter-pro-android:
    name: HEIC Converter Pro - Android
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      android_signing:
        - keystore_reference
      groups:
        - google_play
      vars:
        FCI_KEYSTORE_PATH: Encrypted(...) # Add your keystore path
        FCI_KEYSTORE_PASSWORD: Encrypted(...) # Add your keystore password
        FCI_KEY_ALIAS: Encrypted(...) # Add your key alias
        FCI_KEY_PASSWORD: Encrypted(...) # Add your key password
        GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS: Encrypted(...) # Add your Google Play credentials
        GOOGLE_PLAY_PACKAGE_NAME: com.heicconverter.pro
        GOOGLE_PLAY_TRACK: internal # or alpha, beta, production
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
      - name: Build APK
        script: |
          flutter build apk --release --build-name=1.0.$BUILD_NUMBER --build-number=$BUILD_NUMBER
      - name: Build App Bundle
        script: |
          flutter build appbundle --release --build-name=1.0.$BUILD_NUMBER --build-number=$BUILD_NUMBER
    artifacts:
      - build/app/outputs/**/*.apk
      - build/app/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: false

  heic-converter-pro-ios:
    name: HEIC Converter Pro - iOS
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      integrations:
        app_store_connect:
          - apple_id
      vars:
        APP_STORE_CONNECT_ISSUER_ID: Encrypted(...) # Add your issuer ID
        APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(...) # Add your key ID
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(...) # Add your private key
        CERTIFICATE_PRIVATE_KEY: Encrypted(...) # Add your certificate private key
        BUNDLE_ID: com.heicconverter.pro
    scripts:
      - name: Set up keychain to be used for codesigning
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create
      - name: Set up signing certificate
        script: |
          keychain add-certificates
      - name: Set up provisioning profile
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
      - name: Build iOS
        script: |
          flutter build ipa --release --build-name=1.0.$BUILD_NUMBER --build-number=$BUILD_NUMBER
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - "Testers"

  heic-converter-pro-test:
    name: HEIC Converter Pro - Test Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
      - name: Build Debug APK
        script: |
          flutter build apk --debug
    artifacts:
      - build/app/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
